# Generated by Django 2.1.1 on 2018-12-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookinfo_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.Reader'),
        ),
    ]
