# Generated by Django 2.1.1 on 2018-12-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='phone',
            field=models.CharField(default='12312341234', max_length=11),
        ),
    ]
